import type { CatalogConsumerIntel } from "./types";

export const PAIN_CONSUMERS: Record<string, CatalogConsumerIntel> = {
  "pain-quiet": {
    opening:
      "It rustles when you sit or walk. Tap an answer, or drag a slider. I just need to know how it feels for you.",
    whyItHappens:
      "Plastic on the outside rustles when you walk, sit, or use paper nearby. Cloth is quieter. A bigger, more absorbent pad is usually louder and easier to see. Quiet and maximum capacity pull in opposite directions.",
    triedFirst: [
      "Buying the pack that said it was the most absorbent",
      "Wearing it under looser clothes only",
      "Doubling up, or adding a liner on top",
      "Waiting to change until you get home",
    ],
    usuallyFails: [
      "Choosing the highest capacity, then hearing it when you sit down",
      "Assuming a higher price means it will be quieter",
    ],
    mistakes: [
      "Do not pick the biggest pad if noise is the complaint. More film usually means more rustle.",
      "Do not judge it in an empty bathroom. Chairs and quiet rooms are the real test.",
    ],
    tradeoffs: [
      "Cloth-backed underwear is usually the quietest everyday option. It will not hold as much as a max pad.",
      "A thin liner disappears under clothes. You will change more often.",
      "A high-absorbency guard lasts longer. It is often the loudest and the easiest to see.",
    ],
    profile:
      "Most often people who need to sit, walk, or travel without the product giving them away.",
    recentlyChanged:
      "People now search for quiet and discreet, not only for absorbency.",
    diagnostic: quietDiagnostic(),
  },
  "pain-thin": {
    opening:
      "It works at home, then it shows at work. Tap an answer, or drag a slider. I just need to know how it feels for you.",
    whyItHappens:
      "A wide pad prints through fitted clothes. It gets more obvious as it takes on wetness by the afternoon. Thin liners hide until they fail. Underwear hides better than a rectangle. If you need all-day heavy protection, a skinny product will lie to you.",
    triedFirst: [
      "Sizing down so it does not show",
      "Wearing darker or looser trousers",
      "Changing twice before lunch",
      "Using a pad that works at home",
    ],
    usuallyFails: [
      "Picking the thinnest liner, then leaking in a meeting",
      "Sizing up for safety, then seeing it through the fabric",
    ],
    mistakes: [
      "Do not treat thin as all-day. Fitted clothes and a heavy need are different jobs.",
      "Do not judge it in the bathroom mirror at 7am. Outline shows up by mid-afternoon.",
    ],
    tradeoffs: [
      "A thin liner is the least visible. You will change more often.",
      "Cloth-backed underwear hides better than a rectangle and lasts longer than a liner.",
      "A high-absorbency guard lasts a workday. It usually prints through tailored clothes.",
    ],
    profile:
      "Most often people in fitted workwear who need to last a meeting block without it showing.",
    recentlyChanged:
      "Return-to-office and fitted clothes made “does it show” a daily problem.",
    diagnostic: thinDiagnostic(),
  },
  "pain-sunscreen": {
    opening:
      "Sunscreen stings your eyes. Tap an answer, or drag a slider. I just need to know how it feels for you.",
    whyItHappens:
      "The formula moves with sweat and tears. What burns around the eye is often the filter and the fragrance, not the SPF number. A sport bottle that stays on in sweat often runs into your eyes. A fluid mineral is usually kinder around the eye, and it can leave a white film.",
    triedFirst: [
      "An “invisible” or sport SPF",
      "Keeping it away from the eyes",
      "Wearing sunglasses to hide the sting",
      "Skipping sunscreen around the eyes",
    ],
    usuallyFails: [
      "Picking a sweat-proof sport formula, then feeling it burn by lunch",
      "Assuming a higher SPF will sting less",
    ],
    mistakes: [
      "Do not pick the bottle that wins a sweat test if sting is the complaint.",
      "Do not chase the highest SPF number. The one that stays out of your eyes is the one you will actually wear.",
    ],
    tradeoffs: [
      "A fluid mineral is usually kinder around the eyes. Watch for a white film.",
      "A sport chemical stays on in sweat. It is more likely to migrate into your eyes.",
    ],
    profile:
      "Most often people who wear SPF every day — commuting, walking, or under makeup — and will not tolerate sting.",
    recentlyChanged:
      "Daily SPF plus outdoor commuting made sting a daily problem, not a beach problem.",
    diagnostic: sunscreenDiagnostic(),
  },
  "pain-vacuum": {
    opening:
      "The vacuum works. The dog does not. Tap an answer, or drag a slider. I just need to know how it feels for you.",
    whyItHappens:
      "Dogs react to the pitch, the sudden start, and you chasing a loud stick. A quieter stick helps the ears. It does not stop the visual threat. A robot you can run while the dog is out removes the confrontation. More suction does not fix fear.",
    triedFirst: [
      "A quieter stick vacuum",
      "Vacuuming only when the dog is in another room",
      "Treats, or trying to get the dog used to it",
      "Waiting until someone can take the dog out",
    ],
    usuallyFails: [
      "Buying a quieter stick, then still not being able to clean with the dog in the room",
      "Assuming more suction will finish the job faster, so the fear lasts less",
    ],
    mistakes: [
      "Do not buy more power if the dog panics when you pick the machine up.",
      "Do not test it for two minutes. The start-up is often the worst part.",
    ],
    tradeoffs: [
      "A quiet stick is quieter in your hand. You are still the person holding a wand.",
      "A scheduled robot can run while the dog is out. It picks up less in one pass than a stick.",
    ],
    profile:
      "Most often people in flats or open-plan rooms who cannot clean because the dog hides or shakes.",
    recentlyChanged:
      "More dogs in smaller homes made this a weekly search, not a joke.",
    diagnostic: vacuumDiagnostic(),
  },
  "pain-bunion": {
    opening:
      "Shoes rub your bunions. Tap an answer, or drag a slider. I just need to know how it feels for you.",
    whyItHappens:
      "A pointed toe and a seam over the joint turn every step into friction. Extra cushion under the heel does not stop that. Wide-fit still rubs if the toe is tapered. Room over the joint, and a seam that sits somewhere else, is the actual fix.",
    triedFirst: [
      "A cushioned trainer",
      "A wide-fit pair that still had a pointed toe",
      "Plasters, or stretching the shoe",
      "Saving “nice” shoes for short outings",
    ],
    usuallyFails: [
      "Buying extra cushion, then limping because the toe is still pointed",
      "Choosing a shoe that looks orthopaedic, then finding the seam still sits on the joint",
    ],
    mistakes: [
      "Do not treat standing-cushion and bunion-room as the same job.",
      "Do not judge a shoe by “wide fit” on the box. The toe shape and the seam matter more.",
    ],
    tradeoffs: [
      "A wide, foot-shaped toe with few seams at the joint solves the rub. It may not look like a fashion trainer.",
      "A high-cushion trainer helps if you stand all day. It often still tapers over the bunion.",
    ],
    profile:
      "Most often people on their feet for work or a commute, looking for a pair they will actually leave the house in.",
    recentlyChanged:
      "People now search for this joint, not for generic comfort shoes.",
    diagnostic: bunionDiagnostic(),
  },
  "pain-ebike-range": {
    opening:
      "The battery dies before you get home. Tap an answer, or drag a slider. I just need to know how the ride feels.",
    whyItHappens:
      "The sticker range is measured on flat ground, in mild weather, on a low assist setting. Hills, cold, and stop-start traffic cut that number. A hub motor fades on a climb. A mid-drive keeps assist when you slow down. A folding bike is easy to carry and usually packs a smaller battery.",
    triedFirst: [
      "Riding on a lower assist setting to save charge",
      "Charging at work, or carrying a spare charger",
      "Buying the bike with the biggest advertised kilometre number",
      "Pedalling harder on hills, then arriving exhausted anyway",
    ],
    usuallyFails: [
      "Trusting the sticker range measured on the flat",
      "Choosing a folding bike for the train, then running out before the station",
      "Paying more for a bigger advertised number that still dies on hills and cold mornings",
    ],
    mistakes: [
      "Do not treat advertised range and your commute as the same number.",
      "Do not buy a long-range frame if you have to carry it up stairs. The extra cells are why it lasts — and why it is heavy.",
    ],
    tradeoffs: [
      "A mid-drive holds assist on hills. It is still heavy for a train.",
      "A folding hub-motor bike is easy to carry. The battery usually dies first on climbs.",
      "A long-range commuter survives the week. You will not want to lift it.",
    ],
    profile:
      "Most often people who replaced a car or bus trip and then found the battery did not match the route.",
    recentlyChanged:
      "More daily e-bike commutes made this a weekday problem, not a weekend leisure complaint.",
    diagnostic: ebikeRangeDiagnostic(),
  },
};

function quietDiagnostic(): CatalogConsumerIntel["diagnostic"] {
  return [
    {
      id: "discomfort",
      prompt: "What bothers you first?",
      ask: "What bothers you first?",
      chart: "What bothers you",
      control: "choice",
      options: [
        {
          id: "rustle",
          label: "Someone might hear it",
          emphasize: ["noise"],
          factors: ["a quiet outside", "cloth not plastic"],
          profileLabel: "someone might hear it",
          hear: "Someone might hear it. Plastic on the outside is usually what rustles. A bigger pad often makes that worse.",
          nextAsk: "How bad is it? Drag until it feels right.",
        },
        {
          id: "show",
          label: "It shows under clothes",
          emphasize: ["bulk"],
          factors: ["a low outline", "a shape that hides"],
          profileLabel: "it shows under clothes",
          hear: "It shows. A wide pad prints through. Underwear hides better than a rectangle.",
          nextAsk: "How bad is it? Drag until it feels right.",
        },
        {
          id: "leak",
          label: "It does not last long enough",
          emphasize: ["absorbency"],
          factors: ["enough capacity", "time between changes"],
          profileLabel: "it does not last",
          hear: "It does not last. Then we cannot pick the quietest option if it will fail you.",
          nextAsk: "How bad is it? Drag until it feels right.",
        },
      ],
    },
    {
      id: "severity",
      prompt: "How bad is it?",
      ask: "How bad is it?",
      chart: "How bad",
      control: "slider",
      sliderLow: "A bit worrying",
      sliderHigh: "I will not go out",
      options: [
        {
          id: "nudge",
          label: "A bit worrying — I still go",
          emphasize: ["price"],
          factors: ["a quieter everyday cut"],
          profileLabel: "a bit worrying",
          hear: "A bit worrying. We should still fix it. You should not have to listen for it all day.",
          nextAsk: "How long do you need it to last? Drag to match.",
        },
        {
          id: "adjust",
          label: "I keep checking, or sitting still",
          emphasize: ["noise"],
          factors: ["a quiet outside", "cloth not plastic"],
          profileLabel: "you keep checking",
          hear: "You keep checking. The product is running the day, not you.",
          nextAsk: "How long do you need it to last? Drag to match.",
        },
        {
          id: "off",
          label: "I change plans so I can go home",
          emphasize: ["noise", "bulk"],
          factors: ["a quiet outside", "a low outline"],
          profileLabel: "you change plans",
          hear: "You change plans. Then quiet and hidden both matter. We will say the capacity tradeoff out loud.",
          nextAsk: "How long did you need it to last? Drag to match.",
        },
        {
          id: "stop",
          label: "I will not go out in it",
          emphasize: ["noise", "bulk", "comfort"],
          factors: ["a quiet outside", "a low outline", "a comfortable waist"],
          profileLabel: "you will not go out in it",
          hear: "You will not go out in it. Then this has to feel ordinary, not like a medical product.",
          nextAsk: "How long did you need it to last? Drag to match.",
        },
      ],
    },
    {
      id: "duration",
      prompt: "How long do you need it to last?",
      ask: "How long do you need it to last?",
      chart: "How long",
      control: "slider",
      sliderLow: "A few hours",
      sliderHigh: "Overnight",
      options: [
        {
          id: "short",
          label: "A few hours",
          emphasize: ["noise", "bulk"],
          factors: ["a quiet outside", "a low outline"],
          profileLabel: "a few hours",
          hear: "A few hours. Then we can pick quiet first. You can change when you need to.",
          nextAsk: "When does it give you away?",
        },
        {
          id: "medium",
          label: "Half a day",
          emphasize: ["noise", "absorbency"],
          factors: ["a quiet outside", "enough capacity"],
          profileLabel: "half a day",
          hear: "Half a day. A skinny liner may not last that. Quiet underwear is usually the middle path.",
          nextAsk: "When does it give you away?",
        },
        {
          id: "long",
          label: "A full day",
          emphasize: ["absorbency", "comfort"],
          factors: ["enough capacity", "a comfortable waist"],
          profileLabel: "a full day",
          hear: "A full day. The quietest option may not hold that. I will not pretend it will.",
          nextAsk: "When does it give you away?",
        },
        {
          id: "night",
          label: "Overnight",
          emphasize: ["absorbency"],
          factors: ["enough capacity"],
          profileLabel: "overnight",
          hear: "Overnight. Capacity has to win. Quiet still matters if someone is in the next room.",
          nextAsk: "When does it give you away?",
        },
      ],
    },
    {
      id: "onset",
      prompt: "When does it give you away?",
      ask: "When does it give you away?",
      chart: "When",
      control: "choice",
      options: [
        {
          id: "sit",
          label: "When I sit down",
          emphasize: ["noise"],
          factors: ["a quiet outside", "cloth not plastic"],
          profileLabel: "when you sit",
          hear: "When you sit. Chairs are the test. Plastic film is usually what people hear.",
          nextAsk: "What do you wear now?",
        },
        {
          id: "walk",
          label: "When I walk",
          emphasize: ["noise", "bulk"],
          factors: ["a quiet outside", "a shape that hides"],
          profileLabel: "when you walk",
          hear: "When you walk. The product is moving at the hip. A stiff outside will speak.",
          nextAsk: "What do you wear now?",
        },
        {
          id: "always",
          label: "Most of the time",
          emphasize: ["noise", "bulk", "comfort"],
          factors: ["a quiet outside", "a low outline", "a comfortable waist"],
          profileLabel: "most of the time",
          hear: "Most of the time. Then we pick what disappears into an ordinary day.",
          nextAsk: "What do you wear now?",
        },
      ],
    },
    {
      id: "current",
      prompt: "What do you wear now?",
      ask: "What do you wear now?",
      chart: "What you wear",
      control: "list",
      options: [
        {
          id: "plastic",
          label: "A pad with a plastic outside",
          emphasize: ["noise"],
          factors: ["cloth not plastic", "a quiet outside"],
          profileLabel: "a plastic-backed pad",
          hear: "A plastic outside. That is usually the rustle. Cloth is quieter. It may hold less.",
          nextAsk: "What are you wearing over it?",
        },
        {
          id: "underwear",
          label: "Underwear that looks like ordinary pants",
          emphasize: ["comfort", "noise"],
          factors: ["a comfortable waist", "a quiet outside"],
          profileLabel: "underwear-style",
          hear: "Underwear-style. That is already closer. If it still rustles, the outside is still too much like film.",
          nextAsk: "What are you wearing over it?",
        },
        {
          id: "liner",
          label: "A thin liner",
          emphasize: ["bulk"],
          factors: ["a low outline"],
          profileLabel: "a thin liner",
          hear: "A thin liner. It hides. If the complaint is noise and lasting, it may be too little.",
          nextAsk: "What are you wearing over it?",
        },
        {
          id: "mix",
          label: "I keep switching",
          emphasize: ["noise", "bulk"],
          factors: ["a quiet outside", "a low outline"],
          profileLabel: "you keep switching",
          hear: "You keep switching. Nothing has been quiet and hidden enough yet.",
          nextAsk: "What are you wearing over it?",
        },
      ],
    },
    {
      id: "clothes",
      prompt: "What are you wearing over it?",
      ask: "What are you wearing over it?",
      chart: "Clothes",
      control: "list",
      options: [
        {
          id: "loose",
          label: "Loose clothes",
          emphasize: ["noise"],
          factors: ["a quiet outside"],
          profileLabel: "loose clothes",
          hear: "Loose clothes. Outline is easier. Noise is still the giveaway.",
          nextAsk: "Where does this matter most?",
        },
        {
          id: "work",
          label: "Work trousers or a skirt",
          emphasize: ["noise", "bulk"],
          factors: ["a quiet outside", "a low outline"],
          profileLabel: "work clothes",
          hear: "Work clothes. Chairs and quiet rooms expose rustle. Tailoring exposes outline.",
          nextAsk: "Where does this matter most?",
        },
        {
          id: "fitted",
          label: "Leggings or something fitted",
          emphasize: ["bulk"],
          factors: ["a low outline", "a shape that hides"],
          profileLabel: "fitted clothes",
          hear: "Fitted clothes. Then shape matters more than a big pad.",
          nextAsk: "Where does this matter most?",
        },
      ],
    },
    {
      id: "setting",
      prompt: "Where does this matter most?",
      ask: "Where does this matter most?",
      chart: "Where",
      control: "choice",
      options: [
        {
          id: "work",
          label: "At work",
          emphasize: ["noise", "bulk"],
          factors: ["a quiet outside", "a low outline"],
          profileLabel: "at work",
          hear: "At work. This has to last a sitting day, not a bathroom test.",
          nextAsk: "What matters more: staying quiet, or lasting longer? Drag to match.",
        },
        {
          id: "home",
          label: "At home",
          emphasize: ["comfort", "absorbency"],
          factors: ["a comfortable waist", "enough capacity"],
          profileLabel: "at home",
          hear: "At home. Comfort can come first. Quiet still matters if someone else is there.",
          nextAsk: "What matters more: staying quiet, or lasting longer? Drag to match.",
        },
        {
          id: "out",
          label: "Out in public",
          emphasize: ["noise", "bulk"],
          factors: ["a quiet outside", "a low outline"],
          profileLabel: "out in public",
          hear: "Out in public. How it sounds and how it looks both matter.",
          nextAsk: "What matters more: staying quiet, or lasting longer? Drag to match.",
        },
        {
          id: "all",
          label: "All of those",
          emphasize: ["noise", "bulk", "comfort"],
          factors: ["a quiet outside", "a low outline", "a comfortable waist"],
          profileLabel: "most of the time",
          hear: "All of those. Then we plan for the hardest moment, not the easiest room.",
          nextAsk: "What matters more: staying quiet, or lasting longer? Drag to match.",
        },
      ],
    },
    {
      id: "silence",
      prompt: "What matters more: staying quiet, or lasting longer?",
      ask: "What matters more: staying quiet, or lasting longer?",
      chart: "Quiet or lasting",
      control: "slider",
      sliderLow: "Staying quiet",
      sliderHigh: "Lasting longer",
      options: [
        {
          id: "quiet",
          label: "Staying quiet — I can change",
          emphasize: ["noise", "bulk"],
          factors: ["a quiet outside", "cloth not plastic"],
          profileLabel: "quiet first",
          hear: "Quiet first. Then we do not have to chase maximum capacity. Cloth-backed is usually the kind that does not speak.",
          nextAsk: "What have you already tried? You can pick more than one.",
        },
        {
          id: "either",
          label: "In the middle — I need both",
          emphasize: ["noise", "absorbency"],
          factors: ["a quiet outside", "enough capacity"],
          profileLabel: "you need both",
          hear: "You need both. Underwear-style is usually that middle. A max pad will still rustle.",
          nextAsk: "What have you already tried? You can pick more than one.",
        },
        {
          id: "last",
          label: "Lasting longer — I cannot change often",
          emphasize: ["absorbency"],
          factors: ["enough capacity"],
          profileLabel: "lasting first",
          hear: "Lasting first. That often means more bulk and more noise. I will say that clearly before you buy.",
          nextAsk: "What have you already tried? You can pick more than one.",
        },
      ],
    },
    {
      id: "tried",
      prompt: "What have you already tried?",
      ask: "What have you already tried? You can pick more than one.",
      chart: "Already tried",
      control: "multi",
      options: [
        {
          id: "max",
          label: "The most absorbent pack",
          emphasize: ["noise"],
          factors: ["a quiet outside", "cloth not plastic"],
          profileLabel: "you tried the biggest pack",
          hear: "The biggest pack. That is the usual miss. Highest capacity is often the noisiest.",
        },
        {
          id: "loose",
          label: "Only wearing it under loose clothes",
          emphasize: ["bulk"],
          factors: ["a low outline"],
          profileLabel: "you hid it under loose clothes",
          hear: "Loose clothes hide outline. They do not stop a plastic outside from rustling.",
        },
        {
          id: "double",
          label: "Doubling up",
          emphasize: ["bulk", "noise"],
          factors: ["a low outline", "a quiet outside"],
          profileLabel: "you doubled up",
          hear: "Doubling up adds bulk and often adds noise. The next one has to fit the job, not stack extras.",
        },
        {
          id: "none",
          label: "Nothing yet",
          emphasize: [],
          factors: [],
          profileLabel: "nothing yet",
          hear: "Nothing yet. Then we can skip the usual wrong buy — the loud high-capacity pack.",
        },
      ],
    },
  ];
}

function thinDiagnostic(): CatalogConsumerIntel["diagnostic"] {
  return [
    {
      id: "discomfort",
      prompt: "What shows up first at work?",
      ask: "What shows up first at work?",
      chart: "What shows",
      control: "choice",
      options: [
        {
          id: "line",
          label: "A line under my clothes",
          emphasize: ["bulk"],
          factors: ["a low outline", "a shape that hides"],
          profileLabel: "a line under clothes",
          hear: "A line under clothes. A rectangle prints. Underwear hides better. A skinny liner hides best, and it may not last.",
          nextAsk: "How bad is it? Drag until it feels right.",
        },
        {
          id: "rustle",
          label: "It rustles in a quiet room",
          emphasize: ["noise"],
          factors: ["a quiet outside", "cloth not plastic"],
          profileLabel: "it rustles at work",
          hear: "It rustles at work. Open offices and meeting rooms expose that. Plastic film is usually the sound.",
          nextAsk: "How bad is it? Drag until it feels right.",
        },
        {
          id: "bulk",
          label: "It feels bulky by lunch",
          emphasize: ["bulk", "comfort"],
          factors: ["a low outline", "a comfortable waist"],
          profileLabel: "it feels bulky",
          hear: "It feels bulky by lunch. Wetness makes outline worse. Thin at 7am is not thin at 3pm.",
          nextAsk: "How bad is it? Drag until it feels right.",
        },
      ],
    },
    {
      id: "severity",
      prompt: "How bad is it?",
      ask: "How bad is it?",
      chart: "How bad",
      control: "slider",
      sliderLow: "A bit obvious",
      sliderHigh: "I cannot wear it to work",
      options: [
        {
          id: "nudge",
          label: "A bit obvious — I still wear it",
          emphasize: ["price"],
          factors: ["a lower outline"],
          profileLabel: "a bit obvious",
          hear: "A bit obvious. We should still fix it. You should not have to dress around it.",
          nextAsk: "How long do you need to go? Drag to match a workday.",
        },
        {
          id: "adjust",
          label: "I keep pulling clothes over it",
          emphasize: ["bulk"],
          factors: ["a low outline", "a shape that hides"],
          profileLabel: "you keep covering it",
          hear: "You keep covering it. The product is winning. A different shape will help more than a darker colour.",
          nextAsk: "How long do you need to go? Drag to match a workday.",
        },
        {
          id: "off",
          label: "I change before a meeting",
          emphasize: ["bulk", "absorbency"],
          factors: ["a low outline", "enough for a meeting"],
          profileLabel: "you change before meetings",
          hear: "You change before meetings. Then it has to last a block, not just look thin in the morning.",
          nextAsk: "How long did you need to go? Drag to match.",
        },
        {
          id: "stop",
          label: "I cannot wear it to work",
          emphasize: ["bulk", "noise", "comfort"],
          factors: ["a low outline", "a quiet outside", "a comfortable waist"],
          profileLabel: "you cannot wear it to work",
          hear: "You cannot wear it to work. Then hiding and lasting both have to be true, or we pick which one you cannot drop.",
          nextAsk: "How long did you need to go? Drag to match.",
        },
      ],
    },
    {
      id: "duration",
      prompt: "How long do you need to go?",
      ask: "How long do you need to go?",
      chart: "How long",
      control: "slider",
      sliderLow: "A short meeting",
      sliderHigh: "A full workday",
      options: [
        {
          id: "short",
          label: "A short meeting",
          emphasize: ["bulk"],
          factors: ["a low outline"],
          profileLabel: "a short meeting",
          hear: "A short meeting. A thin liner can hide for that. Do not stretch it into a whole day.",
          nextAsk: "What do you wear to work, over it?",
        },
        {
          id: "medium",
          label: "A morning or an afternoon",
          emphasize: ["bulk", "absorbency"],
          factors: ["a low outline", "enough for a meeting block"],
          profileLabel: "a half day",
          hear: "A half day. Underwear-style is usually the balance. A skinny liner often fails before lunch.",
          nextAsk: "What do you wear to work, over it?",
        },
        {
          id: "long",
          label: "A full workday",
          emphasize: ["absorbency", "comfort"],
          factors: ["enough capacity", "a comfortable waist"],
          profileLabel: "a full workday",
          hear: "A full workday. The thinnest option will probably lie to you. I will say that before you buy.",
          nextAsk: "What do you wear to work, over it?",
        },
        {
          id: "allday",
          label: "Work plus the commute",
          emphasize: ["absorbency", "bulk", "comfort"],
          factors: ["enough capacity", "a low outline", "a comfortable waist"],
          profileLabel: "work and the commute",
          hear: "Work and the commute. That is a long stretch. Thin and all-day are different jobs.",
          nextAsk: "What do you wear to work, over it?",
        },
      ],
    },
    {
      id: "current",
      prompt: "What do you wear to work, over it?",
      ask: "What do you wear to work, over it?",
      chart: "Work clothes",
      control: "list",
      options: [
        {
          id: "trousers",
          label: "Tailored trousers",
          emphasize: ["bulk"],
          factors: ["a low outline", "a shape that hides"],
          profileLabel: "tailored trousers",
          hear: "Tailored trousers. Outline shows. A rectangle is the usual miss.",
          nextAsk: "What do you wear now, underneath?",
        },
        {
          id: "skirt",
          label: "A fitted skirt",
          emphasize: ["bulk"],
          factors: ["a low outline"],
          profileLabel: "a fitted skirt",
          hear: "A fitted skirt. Rise and width both print. Underwear hides better than a pad with wings.",
          nextAsk: "What do you wear now, underneath?",
        },
        {
          id: "leggings",
          label: "Leggings",
          emphasize: ["bulk", "noise"],
          factors: ["a low outline", "a quiet outside"],
          profileLabel: "leggings",
          hear: "Leggings. Everything shows. Thin has to be true, not just the pack claim.",
          nextAsk: "What do you wear now, underneath?",
        },
        {
          id: "mix",
          label: "It depends on the day",
          emphasize: ["bulk"],
          factors: ["a low outline"],
          profileLabel: "it depends on the day",
          hear: "It depends. We plan for the tightest outfit, not the loosest.",
          nextAsk: "What do you wear now, underneath?",
        },
      ],
    },
    {
      id: "under",
      prompt: "What do you wear now, underneath?",
      ask: "What do you wear now, underneath?",
      chart: "What you wear",
      control: "list",
      options: [
        {
          id: "pad",
          label: "A regular pad",
          emphasize: ["bulk"],
          factors: ["a low outline", "a shape that hides"],
          profileLabel: "a regular pad",
          hear: "A regular pad. That is a rectangle. It prints through tailored clothes.",
          nextAsk: "How heavy is the need, on a workday?",
        },
        {
          id: "liner",
          label: "A thin liner",
          emphasize: ["absorbency"],
          factors: ["enough for a meeting block"],
          profileLabel: "a thin liner",
          hear: "A thin liner. It hides. If you are leaking before lunch, it is the wrong job.",
          nextAsk: "How heavy is the need, on a workday?",
        },
        {
          id: "underwear",
          label: "Protective underwear",
          emphasize: ["comfort", "noise"],
          factors: ["a comfortable waist", "a quiet outside"],
          profileLabel: "protective underwear",
          hear: "Protective underwear. Better shape. If it still shows, the rise or the wetness is the problem.",
          nextAsk: "How heavy is the need, on a workday?",
        },
        {
          id: "mix",
          label: "I keep switching",
          emphasize: ["bulk", "absorbency"],
          factors: ["a low outline", "enough for a meeting block"],
          profileLabel: "you keep switching",
          hear: "You keep switching. Home and work are different jobs. We pick for work.",
          nextAsk: "How heavy is the need, on a workday?",
        },
      ],
    },
    {
      id: "need",
      prompt: "How heavy is the need, on a workday?",
      ask: "How heavy is the need, on a workday?",
      chart: "How heavy",
      control: "slider",
      sliderLow: "Light",
      sliderHigh: "Heavy",
      options: [
        {
          id: "light",
          label: "Light — a liner should do",
          emphasize: ["bulk", "price"],
          factors: ["a low outline"],
          profileLabel: "a light need",
          hear: "A light need. Then thin can be true. We still keep it quiet in a meeting room.",
          nextAsk: "Where at work does it bother you most?",
        },
        {
          id: "mid",
          label: "In the middle — I need a few hours",
          emphasize: ["bulk", "absorbency"],
          factors: ["a low outline", "enough for a meeting block"],
          profileLabel: "a few hours of need",
          hear: "A few hours. Underwear-style is usually the workday middle.",
          nextAsk: "Where at work does it bother you most?",
        },
        {
          id: "heavy",
          label: "Heavy — I cannot risk a leak",
          emphasize: ["absorbency"],
          factors: ["enough capacity"],
          profileLabel: "a heavy need",
          hear: "A heavy need. A skinny liner will fail. I will not send you that.",
          nextAsk: "Where at work does it bother you most?",
        },
      ],
    },
    {
      id: "setting",
      prompt: "Where at work does it bother you most?",
      ask: "Where at work does it bother you most?",
      chart: "Where at work",
      control: "choice",
      options: [
        {
          id: "office",
          label: "At my desk, in an open office",
          emphasize: ["noise", "bulk"],
          factors: ["a quiet outside", "a low outline"],
          profileLabel: "at your desk",
          hear: "At your desk. Sitting all day makes outline and rustle both worse.",
          nextAsk: "What matters more: not showing, or lasting the day? Drag to match.",
        },
        {
          id: "meeting",
          label: "In meetings",
          emphasize: ["noise", "absorbency"],
          factors: ["a quiet outside", "enough for a meeting block"],
          profileLabel: "in meetings",
          hear: "In meetings. You cannot change. Quiet and enough capacity both matter.",
          nextAsk: "What matters more: not showing, or lasting the day? Drag to match.",
        },
        {
          id: "commute",
          label: "On the way in",
          emphasize: ["bulk", "comfort"],
          factors: ["a low outline", "a comfortable waist"],
          profileLabel: "on the way in",
          hear: "On the way in. Walking and sitting. It has to hide in motion, not only in a mirror.",
          nextAsk: "What matters more: not showing, or lasting the day? Drag to match.",
        },
      ],
    },
    {
      id: "silence",
      prompt: "What matters more: not showing, or lasting the day?",
      ask: "What matters more: not showing, or lasting the day?",
      chart: "Hide or last",
      control: "slider",
      sliderLow: "Not showing",
      sliderHigh: "Lasting the day",
      options: [
        {
          id: "hide",
          label: "Not showing — I can change",
          emphasize: ["bulk"],
          factors: ["a low outline", "a shape that hides"],
          profileLabel: "not showing first",
          hear: "Not showing first. Then a thin liner can be the kind. Do not ask it to last a full day.",
          nextAsk: "What have you already tried? You can pick more than one.",
        },
        {
          id: "either",
          label: "In the middle — I need both",
          emphasize: ["bulk", "absorbency"],
          factors: ["a low outline", "enough for a meeting block"],
          profileLabel: "you need both",
          hear: "You need both. Underwear-style is usually that middle for work.",
          nextAsk: "What have you already tried? You can pick more than one.",
        },
        {
          id: "last",
          label: "Lasting the day — I cannot keep changing",
          emphasize: ["absorbency"],
          factors: ["enough capacity"],
          profileLabel: "lasting first",
          hear: "Lasting first. That often means more outline. I will say that before you buy.",
          nextAsk: "What have you already tried? You can pick more than one.",
        },
      ],
    },
    {
      id: "tried",
      prompt: "What have you already tried?",
      ask: "What have you already tried? You can pick more than one.",
      chart: "Already tried",
      control: "multi",
      options: [
        {
          id: "smaller",
          label: "Sizing down so it does not show",
          emphasize: ["absorbency"],
          factors: ["enough for a meeting block"],
          profileLabel: "you sized down",
          hear: "Sizing down hides. Then it fails in a meeting. Thin is not the same as all-day.",
        },
        {
          id: "dark",
          label: "Darker or looser trousers",
          emphasize: ["bulk"],
          factors: ["a low outline"],
          profileLabel: "you dressed around it",
          hear: "Dressing around it. The product should fit the clothes you already wear.",
        },
        {
          id: "home",
          label: "The pad that works at home",
          emphasize: ["bulk"],
          factors: ["a low outline", "a shape that hides"],
          profileLabel: "you used the home pad",
          hear: "The home pad. Home and work are different jobs. A rectangle that is fine on the sofa prints at a desk.",
        },
        {
          id: "none",
          label: "Nothing yet",
          emphasize: [],
          factors: [],
          profileLabel: "nothing yet",
          hear: "Nothing yet. Then we can skip the usual miss — too thin for the day, or too bulky for the clothes.",
        },
      ],
    },
  ];
}

function sunscreenDiagnostic(): CatalogConsumerIntel["diagnostic"] {
  return [
    {
      id: "discomfort",
      prompt: "What happens first?",
      ask: "What happens first?",
      chart: "What happens",
      control: "choice",
      options: [
        {
          id: "eyes",
          label: "My eyes sting",
          emphasize: ["sting"],
          factors: ["a formula that stays out of the eyes", "less migration with sweat"],
          profileLabel: "your eyes sting",
          hear: "Your eyes sting. The formula is moving. A sport bottle that stays on in sweat often runs into the eye.",
          nextAsk: "How bad is it? Drag until it feels right.",
        },
        {
          id: "makeup",
          label: "It pills under makeup",
          emphasize: ["wear"],
          factors: ["it sits under makeup", "it does not slip"],
          profileLabel: "it pills under makeup",
          hear: "It pills under makeup. Then the winner is the one that stays put, not the highest number on the bottle.",
          nextAsk: "How bad is it? Drag until it feels right.",
        },
        {
          id: "cast",
          label: "It leaves a white film",
          emphasize: ["cast"],
          factors: ["less white film"],
          profileLabel: "a white film",
          hear: "A white film. Mineral formulas do that more. They are often kinder around the eyes.",
          nextAsk: "How bad is it? Drag until it feels right.",
        },
      ],
    },
    {
      id: "severity",
      prompt: "How bad is it?",
      ask: "How bad is it?",
      chart: "How bad",
      control: "slider",
      sliderLow: "A bit annoying",
      sliderHigh: "I stop using it",
      options: [
        {
          id: "nudge",
          label: "A bit annoying — I still wear it",
          emphasize: ["price"],
          factors: ["a formula you will actually wear"],
          profileLabel: "a bit annoying",
          hear: "A bit annoying. We should still fix it. You should not have to blink through the morning.",
          nextAsk: "How long are you out in it? Drag to match.",
        },
        {
          id: "adjust",
          label: "I keep wiping my eyes",
          emphasize: ["sting"],
          factors: ["a formula that stays out of the eyes"],
          profileLabel: "you keep wiping your eyes",
          hear: "You keep wiping your eyes. That spreads it. The next bottle has to stay put.",
          nextAsk: "How long are you out in it? Drag to match.",
        },
        {
          id: "off",
          label: "I skip it around my eyes",
          emphasize: ["sting"],
          factors: ["a formula that stays out of the eyes"],
          profileLabel: "you skip it around the eyes",
          hear: "You skip it around the eyes. That is how people end up with no protection where they need it.",
          nextAsk: "How long are you out in it? Drag to match.",
        },
        {
          id: "stop",
          label: "I stop using sunscreen",
          emphasize: ["sting", "wear"],
          factors: ["a formula that stays out of the eyes", "it sits under makeup"],
          profileLabel: "you stop using it",
          hear: "You stop using it. Then feeling okay is the whole point. A bottle you will not wear does not count.",
          nextAsk: "How long are you out in it? Drag to match.",
        },
      ],
    },
    {
      id: "duration",
      prompt: "How long are you out in it?",
      ask: "How long are you out in it?",
      chart: "How long",
      control: "slider",
      sliderLow: "A short walk",
      sliderHigh: "Most of the day",
      options: [
        {
          id: "short",
          label: "A short walk or commute",
          emphasize: ["sting"],
          factors: ["a formula that stays out of the eyes"],
          profileLabel: "a short commute",
          hear: "A short commute. If it stings that fast, the formula is already wrong around the eye.",
          nextAsk: "When does it start to sting?",
        },
        {
          id: "medium",
          label: "A couple of hours outside",
          emphasize: ["sting", "protection"],
          factors: ["a formula that stays out of the eyes", "it still sits after a few hours"],
          profileLabel: "a couple of hours",
          hear: "A couple of hours. Sweat tests last that. The eye test is the one that fails.",
          nextAsk: "When does it start to sting?",
        },
        {
          id: "long",
          label: "Most of a workday",
          emphasize: ["wear", "protection"],
          factors: ["it sits under makeup", "it still sits after a few hours"],
          profileLabel: "most of a workday",
          hear: "Most of a workday. It has to sit under makeup or on bare skin until you get home.",
          nextAsk: "When does it start to sting?",
        },
        {
          id: "allday",
          label: "A long day outdoors",
          emphasize: ["protection", "sting"],
          factors: ["it still sits after a few hours", "a formula that stays out of the eyes"],
          profileLabel: "a long day outdoors",
          hear: "A long day outdoors. Stay-on and no-sting pull against each other. I will say that clearly.",
          nextAsk: "When does it start to sting?",
        },
      ],
    },
    {
      id: "onset",
      prompt: "When does it start to sting?",
      ask: "When does it start to sting?",
      chart: "When it stings",
      control: "choice",
      options: [
        {
          id: "now",
          label: "Straight away",
          emphasize: ["sting"],
          factors: ["a formula that stays out of the eyes"],
          profileLabel: "straight away",
          hear: "Straight away. The formula does not agree with the skin around your eye. A different kind, not a higher SPF.",
          nextAsk: "What do you use now?",
        },
        {
          id: "sweat",
          label: "Once I warm up or sweat",
          emphasize: ["sting", "protection"],
          factors: ["less migration with sweat", "a formula that stays out of the eyes"],
          profileLabel: "once you sweat",
          hear: "Once you sweat. That is migration. Sport formulas often do this.",
          nextAsk: "What do you use now?",
        },
        {
          id: "lunch",
          label: "By lunch",
          emphasize: ["sting", "wear"],
          factors: ["a formula that stays out of the eyes", "it sits under makeup"],
          profileLabel: "by lunch",
          hear: "By lunch. A shop test never lasts that long. Your real morning is the test.",
          nextAsk: "What do you use now?",
        },
      ],
    },
    {
      id: "current",
      prompt: "What do you use now?",
      ask: "What do you use now?",
      chart: "What you use",
      control: "list",
      options: [
        {
          id: "sport",
          label: "A sport or sweat-proof SPF",
          emphasize: ["sting"],
          factors: ["a formula that stays out of the eyes", "less migration with sweat"],
          profileLabel: "a sport SPF",
          hear: "A sport SPF. It stays on in sweat. That is often why it finds the eye.",
          nextAsk: "Do you wear it under makeup?",
        },
        {
          id: "invisible",
          label: "An “invisible” or fluid one",
          emphasize: ["sting", "cast"],
          factors: ["a formula that stays out of the eyes"],
          profileLabel: "an invisible SPF",
          hear: "An invisible one. Invisible often still stings. The eye does not care about the finish.",
          nextAsk: "Do you wear it under makeup?",
        },
        {
          id: "mineral",
          label: "A mineral or zinc one",
          emphasize: ["cast"],
          factors: ["less white film"],
          profileLabel: "a mineral SPF",
          hear: "A mineral one. Kinder around the eyes for a lot of people. The film is the usual complaint.",
          nextAsk: "Do you wear it under makeup?",
        },
        {
          id: "skip",
          label: "I have mostly stopped",
          emphasize: ["sting"],
          factors: ["a formula that stays out of the eyes"],
          profileLabel: "you have mostly stopped",
          hear: "You have mostly stopped. Then the next bottle has to be one you will actually put near your eyes.",
          nextAsk: "Do you wear it under makeup?",
        },
      ],
    },
    {
      id: "makeup",
      prompt: "Do you wear it under makeup?",
      ask: "Do you wear it under makeup?",
      chart: "Makeup",
      control: "choice",
      options: [
        {
          id: "yes",
          label: "Yes — under makeup",
          emphasize: ["wear"],
          factors: ["it sits under makeup", "it does not slip"],
          profileLabel: "under makeup",
          hear: "Under makeup. Then pilling and slip matter. The bottle has to sit, not just score well on a sweat test.",
          nextAsk: "Where are you when it bothers you?",
        },
        {
          id: "no",
          label: "No — on bare skin",
          emphasize: ["sting", "cast"],
          factors: ["a formula that stays out of the eyes", "less white film"],
          profileLabel: "on bare skin",
          hear: "On bare skin. Sting and a white film are easier to see. We can pick for the eye first.",
          nextAsk: "Where are you when it bothers you?",
        },
        {
          id: "mix",
          label: "Some days yes, some days no",
          emphasize: ["wear", "sting"],
          factors: ["it sits under makeup", "a formula that stays out of the eyes"],
          profileLabel: "it depends on the day",
          hear: "It depends. We still pick a formula that does not run, with or without makeup.",
          nextAsk: "Where are you when it bothers you?",
        },
      ],
    },
    {
      id: "setting",
      prompt: "Where are you when it bothers you?",
      ask: "Where are you when it bothers you?",
      chart: "Where",
      control: "choice",
      options: [
        {
          id: "commute",
          label: "On the commute or a walk",
          emphasize: ["sting"],
          factors: ["a formula that stays out of the eyes"],
          profileLabel: "on the commute",
          hear: "On the commute. Warmth and moving air. It has to last that, not a bathroom mirror.",
          nextAsk: "What matters more: no sting, or staying on in sweat? Drag to match.",
        },
        {
          id: "desk",
          label: "At my desk, under makeup",
          emphasize: ["wear"],
          factors: ["it sits under makeup"],
          profileLabel: "at your desk",
          hear: "At your desk. Then it has to sit all morning. Sting still matters if you tear up at a screen.",
          nextAsk: "What matters more: no sting, or staying on in sweat? Drag to match.",
        },
        {
          id: "sport",
          label: "When I exercise or get hot",
          emphasize: ["protection", "sting"],
          factors: ["it still sits after a few hours", "less migration with sweat"],
          profileLabel: "when you get hot",
          hear: "When you get hot. Stay-on and no-sting fight. I will not hide that.",
          nextAsk: "What matters more: no sting, or staying on in sweat? Drag to match.",
        },
      ],
    },
    {
      id: "silence",
      prompt: "What matters more: no sting, or staying on in sweat?",
      ask: "What matters more: no sting, or staying on in sweat?",
      chart: "Sting or stay-on",
      control: "slider",
      sliderLow: "No sting",
      sliderHigh: "Staying on",
      options: [
        {
          id: "nosting",
          label: "No sting — I can reapply",
          emphasize: ["sting"],
          factors: ["a formula that stays out of the eyes", "less migration with sweat"],
          profileLabel: "no sting first",
          hear: "No sting first. Then a fluid mineral is usually the kind. Watch for a white film.",
          nextAsk: "What have you already tried? You can pick more than one.",
        },
        {
          id: "either",
          label: "In the middle — I need both",
          emphasize: ["sting", "protection"],
          factors: ["a formula that stays out of the eyes", "it still sits after a few hours"],
          profileLabel: "you need both",
          hear: "You need both. We still start with the eye. A sport bottle that burns will not get used.",
          nextAsk: "What have you already tried? You can pick more than one.",
        },
        {
          id: "stay",
          label: "Staying on — I get very sweaty",
          emphasize: ["protection"],
          factors: ["it still sits after a few hours"],
          profileLabel: "staying on first",
          hear: "Staying on first. That often stings more around the eye. I will say that before you buy.",
          nextAsk: "What have you already tried? You can pick more than one.",
        },
      ],
    },
    {
      id: "tried",
      prompt: "What have you already tried?",
      ask: "What have you already tried? You can pick more than one.",
      chart: "Already tried",
      control: "multi",
      options: [
        {
          id: "sport",
          label: "Sport or sweat-proof SPF",
          emphasize: ["sting"],
          factors: ["a formula that stays out of the eyes"],
          profileLabel: "you tried sport SPF",
          hear: "Sport SPF. That is the usual miss. It stays on in sweat, then it finds the eye.",
        },
        {
          id: "avoid",
          label: "Keeping it away from my eyes",
          emphasize: ["sting"],
          factors: ["a formula that stays out of the eyes"],
          profileLabel: "you kept it away from the eyes",
          hear: "Keeping it away. Then the skin next to the eye has no protection. The next bottle has to be one you can put there.",
        },
        {
          id: "skip",
          label: "Skipping sunscreen there",
          emphasize: ["sting"],
          factors: ["a formula that stays out of the eyes"],
          profileLabel: "you skipped it there",
          hear: "Skipping it there. That is how sting wins. We pick a kind that does not make you do that.",
        },
        {
          id: "none",
          label: "Nothing yet",
          emphasize: [],
          factors: [],
          profileLabel: "nothing yet",
          hear: "Nothing yet. Then we can skip the usual wrong bottle — the sweat-proof one that burns.",
        },
      ],
    },
  ];
}

function vacuumDiagnostic(): CatalogConsumerIntel["diagnostic"] {
  return [
    {
      id: "discomfort",
      prompt: "What scares the dog first?",
      ask: "What scares the dog first?",
      chart: "What scares them",
      control: "choice",
      options: [
        {
          id: "sound",
          label: "The sound",
          emphasize: ["noise"],
          factors: ["a quieter motor", "no sudden start"],
          profileLabel: "the sound",
          hear: "The sound. Pitch and a sudden start are usually worse than how well it picks up hair.",
          nextAsk: "How bad is it? Drag until it feels right.",
        },
        {
          id: "you",
          label: "Me holding it and moving",
          emphasize: ["motion"],
          factors: ["not you chasing a stick", "it can run without you"],
          profileLabel: "you holding it",
          hear: "You holding it. The dog sees a person plus a loud stick. A quieter motor does not change that picture.",
          nextAsk: "How bad is it? Drag until it feels right.",
        },
        {
          id: "move",
          label: "Anything that moves on its own",
          emphasize: ["motion"],
          factors: ["a slow, predictable path", "it can run while the dog is out"],
          profileLabel: "things that move on their own",
          hear: "Anything that moves on its own. Then a robot is not automatically kinder. Running it while the dog is out is.",
          nextAsk: "How bad is it? Drag until it feels right.",
        },
      ],
    },
    {
      id: "severity",
      prompt: "How bad is it?",
      ask: "How bad is it?",
      chart: "How bad",
      control: "slider",
      sliderLow: "A bit unsettled",
      sliderHigh: "The dog panics",
      options: [
        {
          id: "nudge",
          label: "A bit unsettled — I can still clean",
          emphasize: ["price"],
          factors: ["a quieter motor"],
          profileLabel: "a bit unsettled",
          hear: "A bit unsettled. We should still make it easier. You should not have to rush.",
          nextAsk: "How often do you need to vacuum? Drag to match.",
        },
        {
          id: "adjust",
          label: "The dog hides, then I stop",
          emphasize: ["noise", "motion"],
          factors: ["a quieter motor", "not you chasing a stick"],
          profileLabel: "the dog hides",
          hear: "The dog hides, then you stop. The machine works. You cannot use it. That is the whole problem.",
          nextAsk: "How often do you need to vacuum? Drag to match.",
        },
        {
          id: "off",
          label: "I only clean when the dog is out",
          emphasize: ["schedule"],
          factors: ["it can run while the dog is out"],
          profileLabel: "only when the dog is out",
          hear: "Only when the dog is out. Then a machine you can schedule is the kind, not a louder stick you finish faster.",
          nextAsk: "How often do you need to vacuum? Drag to match.",
        },
        {
          id: "stop",
          label: "The dog panics — I cannot use it",
          emphasize: ["noise", "motion", "schedule"],
          factors: ["a quieter motor", "not you chasing a stick", "it can run while the dog is out"],
          profileLabel: "the dog panics",
          hear: "The dog panics. Then feeling safe is the point. More suction does not fix fear.",
          nextAsk: "How often do you need to vacuum? Drag to match.",
        },
      ],
    },
    {
      id: "duration",
      prompt: "How often do you need to vacuum?",
      ask: "How often do you need to vacuum?",
      chart: "How often",
      control: "slider",
      sliderLow: "Now and then",
      sliderHigh: "Most days",
      options: [
        {
          id: "sometimes",
          label: "Now and then",
          emphasize: ["price"],
          factors: ["a quieter motor"],
          profileLabel: "now and then",
          hear: "Now and then. We still pick a kind that does not scare the dog on those days.",
          nextAsk: "What do you use now?",
        },
        {
          id: "weekly",
          label: "A few times a week",
          emphasize: ["noise", "pickup"],
          factors: ["a quieter motor", "it actually picks up hair"],
          profileLabel: "a few times a week",
          hear: "A few times a week. Often enough that the wrong machine keeps costing you both.",
          nextAsk: "What do you use now?",
        },
        {
          id: "daily",
          label: "Most days",
          emphasize: ["schedule", "motion"],
          factors: ["it can run while the dog is out", "not you chasing a stick"],
          profileLabel: "most days",
          hear: "Most days. Then you should not have to hold the machine every time.",
          nextAsk: "What do you use now?",
        },
        {
          id: "constant",
          label: "Hair is constant",
          emphasize: ["pickup", "schedule"],
          factors: ["it actually picks up hair", "it can run while the dog is out"],
          profileLabel: "hair is constant",
          hear: "Hair is constant. Pickup still matters. Fear still comes first, or you will not run it.",
          nextAsk: "What do you use now?",
        },
      ],
    },
    {
      id: "current",
      prompt: "What do you use now?",
      ask: "What do you use now?",
      chart: "What you use",
      control: "list",
      options: [
        {
          id: "stick",
          label: "A stick vacuum I hold",
          emphasize: ["motion"],
          factors: ["not you chasing a stick", "it can run without you"],
          profileLabel: "a stick you hold",
          hear: "A stick you hold. Quieter helps. The dog still sees you plus the wand.",
          nextAsk: "Can the dog be out of the house when you clean?",
        },
        {
          id: "upright",
          label: "A big upright",
          emphasize: ["noise", "motion"],
          factors: ["a quieter motor", "not you chasing a stick"],
          profileLabel: "a big upright",
          hear: "A big upright. Loud and large. That is a lot of threat in one object.",
          nextAsk: "Can the dog be out of the house when you clean?",
        },
        {
          id: "robot",
          label: "A robot already",
          emphasize: ["motion"],
          factors: ["it can run while the dog is out", "a slow, predictable path"],
          profileLabel: "a robot already",
          hear: "A robot already. If the dog still panics, run it while they are out. Do not buy a more aggressive one.",
          nextAsk: "Can the dog be out of the house when you clean?",
        },
        {
          id: "avoid",
          label: "I have mostly stopped vacuuming",
          emphasize: ["schedule", "motion"],
          factors: ["it can run while the dog is out", "not you chasing a stick"],
          profileLabel: "you have mostly stopped",
          hear: "You have mostly stopped. Then the next machine has to work without a stand-off.",
          nextAsk: "Can the dog be out of the house when you clean?",
        },
      ],
    },
    {
      id: "out",
      prompt: "Can the dog be out of the house when you clean?",
      ask: "Can the dog be out of the house when you clean?",
      chart: "Dog out",
      control: "choice",
      options: [
        {
          id: "yes",
          label: "Yes — on a walk or at work",
          emphasize: ["schedule"],
          factors: ["it can run while the dog is out"],
          profileLabel: "the dog can be out",
          hear: "The dog can be out. Then a scheduled robot is usually the kind. You are not in the room with a wand.",
          nextAsk: "Where do you live, with the dog?",
        },
        {
          id: "sometimes",
          label: "Sometimes",
          emphasize: ["schedule", "noise"],
          factors: ["it can run while the dog is out", "a quieter motor"],
          profileLabel: "sometimes the dog can be out",
          hear: "Sometimes. Then we still pick a machine that can run without you, and a quieter option for the days they stay.",
          nextAsk: "Where do you live, with the dog?",
        },
        {
          id: "no",
          label: "No — they are home",
          emphasize: ["noise", "motion"],
          factors: ["a quieter motor", "not you chasing a stick"],
          profileLabel: "the dog is home",
          hear: "The dog is home. Then quieter helps, and you plus a wand is still the hard picture.",
          nextAsk: "Where do you live, with the dog?",
        },
      ],
    },
    {
      id: "setting",
      prompt: "Where do you live, with the dog?",
      ask: "Where do you live, with the dog?",
      chart: "Where",
      control: "choice",
      options: [
        {
          id: "flat",
          label: "A flat or small home",
          emphasize: ["noise"],
          factors: ["a quieter motor"],
          profileLabel: "a small home",
          hear: "A small home. Sound has nowhere to go. Sudden start-up hits harder.",
          nextAsk: "What matters more: quieter in your hand, or cleaning while the dog is out? Drag to match.",
        },
        {
          id: "open",
          label: "Open-plan, one main room",
          emphasize: ["motion", "noise"],
          factors: ["not you chasing a stick", "a quieter motor"],
          profileLabel: "open-plan",
          hear: "Open-plan. The dog cannot leave the noise. You walking the machine is a chase.",
          nextAsk: "What matters more: quieter in your hand, or cleaning while the dog is out? Drag to match.",
        },
        {
          id: "house",
          label: "A house with other rooms",
          emphasize: ["schedule"],
          factors: ["it can run while the dog is out"],
          profileLabel: "a house with other rooms",
          hear: "A house with other rooms. You can separate them. A schedule still beats a stand-off.",
          nextAsk: "What matters more: quieter in your hand, or cleaning while the dog is out? Drag to match.",
        },
      ],
    },
    {
      id: "silence",
      prompt: "What matters more: quieter in your hand, or cleaning while the dog is out?",
      ask: "What matters more: quieter in your hand, or cleaning while the dog is out?",
      chart: "Quiet or away",
      control: "slider",
      sliderLow: "Quieter in my hand",
      sliderHigh: "While the dog is out",
      options: [
        {
          id: "hand",
          label: "Quieter in my hand — I will still hold it",
          emphasize: ["noise", "pickup"],
          factors: ["a quieter motor", "it actually picks up hair"],
          profileLabel: "quieter in your hand",
          hear: "Quieter in your hand. A quiet stick can be the kind. The dog may still hate the wand.",
          nextAsk: "What have you already tried? You can pick more than one.",
        },
        {
          id: "either",
          label: "In the middle — I need both",
          emphasize: ["noise", "schedule"],
          factors: ["a quieter motor", "it can run while the dog is out"],
          profileLabel: "you need both",
          hear: "You need both. A robot you can schedule is usually the bigger fix. A quiet stick is the extra.",
          nextAsk: "What have you already tried? You can pick more than one.",
        },
        {
          id: "away",
          label: "While the dog is out — I do not want a stand-off",
          emphasize: ["schedule", "motion"],
          factors: ["it can run while the dog is out", "not you chasing a stick"],
          profileLabel: "while the dog is out",
          hear: "While the dog is out. Then a scheduled robot is the kind. You are not in the room.",
          nextAsk: "What have you already tried? You can pick more than one.",
        },
      ],
    },
    {
      id: "tried",
      prompt: "What have you already tried?",
      ask: "What have you already tried? You can pick more than one.",
      chart: "Already tried",
      control: "multi",
      options: [
        {
          id: "quiet",
          label: "A quieter stick",
          emphasize: ["motion"],
          factors: ["not you chasing a stick", "it can run without you"],
          profileLabel: "you tried a quieter stick",
          hear: "A quieter stick. That is the usual miss. The sound dropped. You were still the person holding it.",
        },
        {
          id: "room",
          label: "Shutting the dog in another room",
          emphasize: ["schedule"],
          factors: ["it can run while the dog is out"],
          profileLabel: "you shut the dog away",
          hear: "Shutting the dog away. That works until you cannot. A schedule is the same idea, without the scramble.",
        },
        {
          id: "treats",
          label: "Treats, or trying to get them used to it",
          emphasize: ["motion", "noise"],
          factors: ["not you chasing a stick", "a quieter motor"],
          profileLabel: "you tried to get them used to it",
          hear: "Getting them used to it. Some dogs never do. The machine should not need a training plan to be usable.",
        },
        {
          id: "none",
          label: "Nothing yet",
          emphasize: [],
          factors: [],
          profileLabel: "nothing yet",
          hear: "Nothing yet. Then we can skip the usual miss — a powerful stick that still looks like a chase.",
        },
      ],
    },
  ];
}

function bunionDiagnostic(): CatalogConsumerIntel["diagnostic"] {
  return [
    {
      id: "discomfort",
      prompt: "What hurts first?",
      ask: "What hurts first?",
      chart: "What hurts",
      control: "choice",
      options: [
        {
          id: "rub",
          label: "A rub on the joint",
          emphasize: ["width", "seam"],
          factors: ["room over the joint", "no seam on the bunion"],
          profileLabel: "a rub on the joint",
          hear: "A rub on the joint. The toe is too pointed, or a seam sits on it. Cushion under the heel will not stop that.",
          nextAsk: "How bad is it? Drag until it feels right.",
        },
        {
          id: "seam",
          label: "I can feel a seam on it",
          emphasize: ["seam"],
          factors: ["no seam on the bunion", "room over the joint"],
          profileLabel: "a seam on the joint",
          hear: "A seam on the joint. Wide-fit still fails if the stitching is in the wrong place.",
          nextAsk: "How bad is it? Drag until it feels right.",
        },
        {
          id: "stand",
          label: "My feet ache from standing",
          emphasize: ["cushion"],
          factors: ["cushion for standing"],
          profileLabel: "standing ache",
          hear: "Standing ache. Cushion helps that. If the bunion also rubs, we still need room at the toe.",
          nextAsk: "How bad is it? Drag until it feels right.",
        },
      ],
    },
    {
      id: "severity",
      prompt: "How bad is it?",
      ask: "How bad is it?",
      chart: "How bad",
      control: "slider",
      sliderLow: "A bit sore",
      sliderHigh: "I limp or take them off",
      options: [
        {
          id: "nudge",
          label: "A bit sore — I keep them on",
          emphasize: ["price"],
          factors: ["room over the joint"],
          profileLabel: "a bit sore",
          hear: "A bit sore. We should still fix it. You should not have to ignore it until evening.",
          nextAsk: "How long are you on your feet? Drag to match.",
        },
        {
          id: "adjust",
          label: "I keep loosening them, or limping a little",
          emphasize: ["width"],
          factors: ["room over the joint"],
          profileLabel: "you keep adjusting",
          hear: "You keep adjusting. The toe is winning. A softer insole will not make that space.",
          nextAsk: "How long are you on your feet? Drag to match.",
        },
        {
          id: "off",
          label: "I take them off when I can",
          emphasize: ["width", "seam"],
          factors: ["room over the joint", "no seam on the bunion"],
          profileLabel: "you take them off",
          hear: "You take them off. They did not last. The next pair has to last as long as you need.",
          nextAsk: "How long did you need them on? Drag to match.",
        },
        {
          id: "stop",
          label: "I limp, or I cannot finish the day",
          emphasize: ["width", "seam", "cushion"],
          factors: ["room over the joint", "no seam on the bunion", "cushion for standing"],
          profileLabel: "you cannot finish the day",
          hear: "You cannot finish the day. Then room over the joint is the point, not a cushioned heel.",
          nextAsk: "How long did you need them on? Drag to match.",
        },
      ],
    },
    {
      id: "duration",
      prompt: "How long are you on your feet?",
      ask: "How long are you on your feet?",
      chart: "How long",
      control: "slider",
      sliderLow: "A short outing",
      sliderHigh: "All day",
      options: [
        {
          id: "short",
          label: "A short outing",
          emphasize: ["look", "price"],
          factors: ["room over the joint", "a pair you will wear"],
          profileLabel: "a short outing",
          hear: "A short outing. If it hurts that fast, the toe shape is already wrong.",
          nextAsk: "When does it start to hurt?",
        },
        {
          id: "medium",
          label: "A few hours",
          emphasize: ["width"],
          factors: ["room over the joint"],
          profileLabel: "a few hours",
          hear: "A few hours. Shop try-ons last minutes. Your real walk is the test.",
          nextAsk: "When does it start to hurt?",
        },
        {
          id: "long",
          label: "Most of a workday",
          emphasize: ["width", "cushion"],
          factors: ["room over the joint", "cushion for standing"],
          profileLabel: "most of a workday",
          hear: "Most of a workday. Cushion helps standing. It does not fix a pointed toe.",
          nextAsk: "When does it start to hurt?",
        },
        {
          id: "allday",
          label: "All day",
          emphasize: ["width", "seam", "cushion"],
          factors: ["room over the joint", "no seam on the bunion", "cushion for standing"],
          profileLabel: "all day",
          hear: "All day. Soft foam under the heel cannot last that if the joint is trapped.",
          nextAsk: "When does it start to hurt?",
        },
      ],
    },
    {
      id: "onset",
      prompt: "When does it start to hurt?",
      ask: "When does it start to hurt?",
      chart: "When it starts",
      control: "choice",
      options: [
        {
          id: "now",
          label: "Straight away",
          emphasize: ["width"],
          factors: ["room over the joint"],
          profileLabel: "straight away",
          hear: "Straight away. There was never room for the joint. Stretching the shoe will not make that room.",
          nextAsk: "What do you wear now, when it hurts?",
        },
        {
          id: "creep",
          label: "After about half an hour",
          emphasize: ["width", "seam"],
          factors: ["room over the joint", "no seam on the bunion"],
          profileLabel: "after about half an hour",
          hear: "After about half an hour. They feel fine in the shop. Then the seam or the taper wins.",
          nextAsk: "What do you wear now, when it hurts?",
        },
        {
          id: "late",
          label: "By the afternoon",
          emphasize: ["cushion", "width"],
          factors: ["cushion for standing", "room over the joint"],
          profileLabel: "by the afternoon",
          hear: "By the afternoon. Standing fatigue and a trapped joint stack. Cushion alone will not save the bunion.",
          nextAsk: "What do you wear now, when it hurts?",
        },
      ],
    },
    {
      id: "current",
      prompt: "What do you wear now, when it hurts?",
      ask: "What do you wear now, when it hurts?",
      chart: "What you wear",
      control: "list",
      options: [
        {
          id: "trainer",
          label: "Trainers",
          emphasize: ["width"],
          factors: ["room over the joint"],
          profileLabel: "trainers",
          hear: "Trainers. Many still taper at the toe. Cushion is not the same as a foot-shaped front.",
          nextAsk: "Have you already tried a wide pair?",
        },
        {
          id: "work",
          label: "Work shoes",
          emphasize: ["look", "width"],
          factors: ["a pair you will wear", "room over the joint"],
          profileLabel: "work shoes",
          hear: "Work shoes. Looks matter, or you will not wear them. The toe still needs room.",
          nextAsk: "Have you already tried a wide pair?",
        },
        {
          id: "ortho",
          label: "A “comfort” or wide-fit pair",
          emphasize: ["seam"],
          factors: ["no seam on the bunion", "room over the joint"],
          profileLabel: "a wide-fit pair",
          hear: "A wide-fit pair. If it still rubs, the seam or a pointed last is why. Wide on the box is not enough.",
          nextAsk: "Have you already tried a wide pair?",
        },
        {
          id: "mix",
          label: "I keep switching",
          emphasize: ["width", "look"],
          factors: ["room over the joint", "a pair you will wear"],
          profileLabel: "you keep switching",
          hear: "You keep switching. Nothing has been kind to the joint yet, or you will not leave the house in it.",
          nextAsk: "Have you already tried a wide pair?",
        },
      ],
    },
    {
      id: "wide",
      prompt: "Have you already tried a wide pair?",
      ask: "Have you already tried a wide pair?",
      chart: "Wide already",
      control: "choice",
      options: [
        {
          id: "yes",
          label: "Yes — they still rubbed",
          emphasize: ["seam", "width"],
          factors: ["no seam on the bunion", "room over the joint"],
          profileLabel: "wide still rubbed",
          hear: "Wide still rubbed. Then the toe was still pointed, or a seam sat on the joint. We will not send you another pair like that.",
          nextAsk: "Where are you when it hurts most?",
        },
        {
          id: "no",
          label: "Not yet",
          emphasize: ["width"],
          factors: ["room over the joint"],
          profileLabel: "not tried wide yet",
          hear: "Not yet. Wide can help. It only works if the front of the shoe is actually foot-shaped.",
          nextAsk: "Where are you when it hurts most?",
        },
        {
          id: "looks",
          label: "I will not wear the ones that look medical",
          emphasize: ["look"],
          factors: ["a pair you will wear", "room over the joint"],
          profileLabel: "you will not wear medical-looking shoes",
          hear: "You will not wear medical-looking shoes. Then the pair has to look wearable and still leave room at the joint.",
          nextAsk: "Where are you when it hurts most?",
        },
      ],
    },
    {
      id: "setting",
      prompt: "Where are you when it hurts most?",
      ask: "Where are you when it hurts most?",
      chart: "Where",
      control: "choice",
      options: [
        {
          id: "work",
          label: "At work, on my feet",
          emphasize: ["width", "cushion"],
          factors: ["room over the joint", "cushion for standing"],
          profileLabel: "at work",
          hear: "At work. This has to last a standing day, not a walk around the shop.",
          nextAsk: "What matters more: room for the joint, or how they look? Drag to match.",
        },
        {
          id: "walk",
          label: "Walking or commuting",
          emphasize: ["width", "seam"],
          factors: ["room over the joint", "no seam on the bunion"],
          profileLabel: "on the way",
          hear: "On the way. Every step is friction if the toe is tight.",
          nextAsk: "What matters more: room for the joint, or how they look? Drag to match.",
        },
        {
          id: "both",
          label: "Most of the day",
          emphasize: ["width", "seam", "cushion"],
          factors: ["room over the joint", "no seam on the bunion", "cushion for standing"],
          profileLabel: "most of the day",
          hear: "Most of the day. We plan for the longest stretch, not a pair that only looks right.",
          nextAsk: "What matters more: room for the joint, or how they look? Drag to match.",
        },
      ],
    },
    {
      id: "silence",
      prompt: "What matters more: room for the joint, or how they look?",
      ask: "What matters more: room for the joint, or how they look?",
      chart: "Room or looks",
      control: "slider",
      sliderLow: "Room for the joint",
      sliderHigh: "How they look",
      options: [
        {
          id: "room",
          label: "Room for the joint — I will wear them",
          emphasize: ["width", "seam"],
          factors: ["room over the joint", "no seam on the bunion"],
          profileLabel: "room first",
          hear: "Room first. Then a wide, foot-shaped toe is the kind. Looks can come second.",
          nextAsk: "What have you already tried? You can pick more than one.",
        },
        {
          id: "either",
          label: "In the middle — I need both",
          emphasize: ["width", "look"],
          factors: ["room over the joint", "a pair you will wear"],
          profileLabel: "you need both",
          hear: "You need both. We still start with room at the joint. A pair you will not leave the house in does not count.",
          nextAsk: "What have you already tried? You can pick more than one.",
        },
        {
          id: "looks",
          label: "How they look — I will not wear clunky shoes",
          emphasize: ["look"],
          factors: ["a pair you will wear"],
          profileLabel: "looks first",
          hear: "Looks first. Then we still need room at the toe. A pretty pointed trainer will rub.",
          nextAsk: "What have you already tried? You can pick more than one.",
        },
      ],
    },
    {
      id: "tried",
      prompt: "What have you already tried?",
      ask: "What have you already tried? You can pick more than one.",
      chart: "Already tried",
      control: "multi",
      options: [
        {
          id: "cushion",
          label: "A cushioned trainer",
          emphasize: ["width"],
          factors: ["room over the joint"],
          profileLabel: "you tried extra cushion",
          hear: "Extra cushion. That is the usual miss. It helps standing. It does not stop a pointed toe.",
        },
        {
          id: "plaster",
          label: "Plasters, or stretching the shoe",
          emphasize: ["width", "seam"],
          factors: ["room over the joint", "no seam on the bunion"],
          profileLabel: "you tried plasters",
          hear: "Plasters buy a day. The shoe is still the wrong shape.",
        },
        {
          id: "save",
          label: "Saving nicer shoes for short trips",
          emphasize: ["look", "width"],
          factors: ["a pair you will wear", "room over the joint"],
          profileLabel: "you save nice shoes for short trips",
          hear: "Saving nice shoes. Then you need a daily pair that does not rub, and that you will actually wear.",
        },
        {
          id: "none",
          label: "Nothing yet",
          emphasize: [],
          factors: [],
          profileLabel: "nothing yet",
          hear: "Nothing yet. Then we can skip the usual miss — a cushioned trainer with a tapered toe.",
        },
      ],
    },
  ];
}

function ebikeRangeDiagnostic(): CatalogConsumerIntel["diagnostic"] {
  return [
    {
      id: "discomfort",
      prompt: "What goes wrong first?",
      ask: "What goes wrong first?",
      chart: "What goes wrong",
      control: "choice",
      options: [
        {
          id: "range",
          label: "I run out of charge before I get home",
          emphasize: ["range", "hills"],
          factors: ["real-world range", "assist that holds on hills"],
          profileLabel: "you run out of charge",
          hear: "You run out of charge. The sticker number was measured on the flat. Hills and cold cut it.",
          nextAsk: "How bad is it? Drag until it feels right.",
        },
        {
          id: "hills",
          label: "The assist dies on the climb",
          emphasize: ["hills", "range"],
          factors: ["assist that holds on hills", "a motor that does not fade"],
          profileLabel: "assist dies on the climb",
          hear: "Assist dies on the climb. A hub motor fades when you slow down. Then you drain the battery fighting a heavy bike.",
          nextAsk: "How bad is it? Drag until it feels right.",
        },
        {
          id: "lift",
          label: "I cannot lift it onto the train or up stairs",
          emphasize: ["lift"],
          factors: ["a bike you can carry", "a fold that fits a hallway"],
          profileLabel: "you cannot lift it",
          hear: "You cannot lift it. Extra battery is why the long-range bikes last — and why they are heavy.",
          nextAsk: "How bad is it? Drag until it feels right.",
        },
      ],
    },
    {
      id: "severity",
      prompt: "How bad is it?",
      ask: "How bad is it?",
      chart: "How bad",
      control: "slider",
      sliderLow: "A bit annoying",
      sliderHigh: "I get stranded",
      options: [
        {
          id: "nudge",
          label: "A bit annoying — I make it, just",
          emphasize: ["price"],
          factors: ["enough range for the route"],
          profileLabel: "a bit annoying",
          hear: "You make it, just. We should still match the bike to the route, not the sticker.",
          nextAsk: "How long is the ride? Drag to match.",
        },
        {
          id: "adjust",
          label: "I drop to a lower assist to finish",
          emphasize: ["range", "hills"],
          factors: ["real-world range", "assist that holds on hills"],
          profileLabel: "you drop assist to finish",
          hear: "You drop assist to finish. Then the last hill is you versus the weight of the bike.",
          nextAsk: "How long is the ride? Drag to match.",
        },
        {
          id: "off",
          label: "I have walked it home, or charged at work",
          emphasize: ["range", "weather"],
          factors: ["real-world range", "range that survives cold"],
          profileLabel: "you have walked it home",
          hear: "You have walked it home. A bigger advertised number will not fix hills or a cold morning.",
          nextAsk: "How long is the ride? Drag to match.",
        },
        {
          id: "stop",
          label: "I get stranded, or I stopped using it",
          emphasize: ["range", "hills", "weather"],
          factors: ["real-world range", "assist that holds on hills"],
          profileLabel: "you get stranded",
          hear: "You get stranded. Then the next bike has to match the route you actually ride.",
          nextAsk: "How long is the ride you need? Drag to match.",
        },
      ],
    },
    {
      id: "duration",
      prompt: "How long is the ride?",
      ask: "How long is the ride?",
      chart: "How long",
      control: "slider",
      sliderLow: "Under 20 minutes",
      sliderHigh: "Over an hour each way",
      options: [
        {
          id: "short",
          label: "Under 20 minutes each way",
          emphasize: ["hills", "lift"],
          factors: ["assist that holds on hills", "a bike you can carry"],
          profileLabel: "under 20 minutes",
          hear: "A short ride. If you still run out, hills or cold are doing the damage, not the distance.",
          nextAsk: "Do you have to carry it?",
        },
        {
          id: "medium",
          label: "20–40 minutes each way",
          emphasize: ["range", "hills"],
          factors: ["real-world range", "assist that holds on hills"],
          profileLabel: "20–40 minutes",
          hear: "Twenty to forty minutes. That is where sticker range usually falls apart once hills start.",
          nextAsk: "Do you have to carry it?",
        },
        {
          id: "long",
          label: "40–60 minutes each way",
          emphasize: ["range", "weather"],
          factors: ["real-world range", "range that survives cold"],
          profileLabel: "40–60 minutes",
          hear: "Forty to sixty minutes. You need a battery that survives the week, not a one-way test ride.",
          nextAsk: "Do you have to carry it?",
        },
        {
          id: "allday",
          label: "Over an hour each way",
          emphasize: ["range", "weather"],
          factors: ["real-world range", "range that survives cold"],
          profileLabel: "over an hour",
          hear: "Over an hour. A folding bike will usually lose. A long-range frame only works if you never have to lift it.",
          nextAsk: "Do you have to carry it?",
        },
      ],
    },
    {
      id: "carry",
      prompt: "Do you have to carry it?",
      ask: "Do you have to carry it?",
      chart: "Carrying",
      control: "choice",
      options: [
        {
          id: "stairs",
          label: "Yes — stairs or a hallway",
          emphasize: ["lift"],
          factors: ["a bike you can carry"],
          profileLabel: "stairs or a hallway",
          hear: "Stairs or a hallway. Extra battery is extra weight. A folding bike is the usual trade.",
          nextAsk: "What have you already tried? You can pick more than one.",
        },
        {
          id: "train",
          label: "Yes — a train or a car boot",
          emphasize: ["lift", "range"],
          factors: ["a bike you can carry", "enough range to reach the station"],
          profileLabel: "a train or a boot",
          hear: "A train or a boot. Then it has to fold or lift, and still have charge when you get there.",
          nextAsk: "What have you already tried? You can pick more than one.",
        },
        {
          id: "no",
          label: "No — it stays on the ground",
          emphasize: ["range", "hills"],
          factors: ["real-world range", "assist that holds on hills"],
          profileLabel: "it stays on the ground",
          hear: "It stays on the ground. Then we can spend the weight budget on battery and hills.",
          nextAsk: "What have you already tried? You can pick more than one.",
        },
      ],
    },
    {
      id: "tried",
      prompt: "What have you already tried?",
      ask: "What have you already tried? You can pick more than one.",
      chart: "Already tried",
      control: "multi",
      options: [
        {
          id: "eco",
          label: "Riding on a lower assist setting",
          emphasize: ["hills", "range"],
          factors: ["assist that holds on hills"],
          profileLabel: "you drop the assist",
          hear: "Lower assist. That saves charge on the flat. It does not fix a motor that fades on the climb.",
        },
        {
          id: "charge",
          label: "Charging at work, or carrying a charger",
          emphasize: ["range"],
          factors: ["real-world range"],
          profileLabel: "you charge away from home",
          hear: "Charging at work. That is a workaround. The bike still does not match the route.",
        },
        {
          id: "sticker",
          label: "Buying the biggest advertised range",
          emphasize: ["range", "hills"],
          factors: ["real-world range", "assist that holds on hills"],
          profileLabel: "you trusted the sticker",
          hear: "The biggest advertised number. That test was on the flat. Hills and cold still cut it.",
        },
        {
          id: "none",
          label: "Nothing yet",
          emphasize: [],
          factors: [],
          profileLabel: "nothing yet",
          hear: "Nothing yet. Then we can skip the sticker and match the bike to the route.",
        },
      ],
    },
  ];
}
